In [17]:
import pandas as pd
import numpy as np

In [18]:
df=pd.read_csv(r"D:\tmdbdf.csv")
df.head(2000)

,Unnamed: 0,index,id,title,overview,keywords,genres,poster_path
0,0,0,27205,Inception,"Cobb, a skilled thief who commits corporate es...","rescue,mission,dream,airplane,paris,france,vir...","Action,ScienceFiction,Adventure",/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg
1,1,1,157336,Interstellar,The adventures of a group of explorers who mak...,"rescue,future,spacecraft,raceagainsttime,artif...","Adventure,Drama,ScienceFiction",/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg
2,2,2,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,"joker,sadism,chaos,secretidentity,crimefighter...","Drama,Action,Crime,Thriller",/qJ2tW6WMUDux911r6m7haRef0WH.jpg
3,3,3,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","future,society,cultureclash,spacetravel,spacew...","Action,Adventure,Fantasy,ScienceFiction",/kyeqWdyUXW608qlYkRqosgbbJyK.jpg
4,4,4,24428,The Avengers,When an unexpected enemy emerges and threatens...,"newyorkcity,superhero,shield,basedoncomic,alie...","ScienceFiction,Action,Adventure",/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg
...,...,...,...,...,...,...,...,...
1995,1995,1995,8470,John Q,John Quincy Archibald is a father and husband ...,"chicago,illinois,parentchildrelationship,heart...","Drama,Thriller,Crime",/xEE91LvXiqgs7Hmdl44LCzHtFf6.jpg
1996,1996,1996,9574,Flubber,"Professor Phillip Brainard, an absent minded p...","weddingvows,inventor,slime,flight,madscientist...","Comedy,Family,ScienceFiction",/bnKvk04icAyCO1KjqhsaEXBO9aJ.jpg
1997,1997,1997,9894,The Cable Guy,When recently single Steven moves into his new...,"prison,prostitute,karaoke,obsession,darkcomedy...","Comedy,Drama,Thriller",/yyVUQJboripIpoabFU3SkghvnLu.jpg
1998,1998,1998,762968,Do Revenge,A dethroned queen bee at a posh private high s...,"highschool,friendship,femalefriendship,femalep...",Comedy,/akIjKJDHcVN4bzifcEarKVPNpoa.jpg
1999,1999,1999,12242,Mulan II,Fa Mulan gets the surprise of her young life w...,"escape,arrangedmarriage,musical","Animation,Comedy,Family,Action",/8cUIHYXpDFYX6r5ZviQuRKCVLJ2.jpg

In [19]:
df

,Unnamed: 0,index,id,title,overview,keywords,genres,poster_path
0,0,0,27205,Inception,"Cobb, a skilled thief who commits corporate es...","rescue,mission,dream,airplane,paris,france,vir...","Action,ScienceFiction,Adventure",/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg
1,1,1,157336,Interstellar,The adventures of a group of explorers who mak...,"rescue,future,spacecraft,raceagainsttime,artif...","Adventure,Drama,ScienceFiction",/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg
2,2,2,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,"joker,sadism,chaos,secretidentity,crimefighter...","Drama,Action,Crime,Thriller",/qJ2tW6WMUDux911r6m7haRef0WH.jpg
3,3,3,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","future,society,cultureclash,spacetravel,spacew...","Action,Adventure,Fantasy,ScienceFiction",/kyeqWdyUXW608qlYkRqosgbbJyK.jpg
4,4,4,24428,The Avengers,When an unexpected enemy emerges and threatens...,"newyorkcity,superhero,shield,basedoncomic,alie...","ScienceFiction,Action,Adventure",/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg
...,...,...,...,...,...,...,...,...
20995,21067,21067,55758,Midnight FM,Popular TV anchorwoman & late night DJ Ko Sun-...,"radiostation,radio","Thriller,Crime,Action",/8WqtunxSTVFiyBAUYSXbTSh0Vc5.jpg
20996,21068,21068,79990,Desi Boyz,"Two friends lose their jobs, then part bitterl...",NaN,"Comedy,Drama",/2Tga4SJQTKSENOISM5CRIb240LR.jpg
20997,21069,21069,1030419,Legend of the Galactic Heroes: Die Neue These ...,The story focuses on the exploits of rivals Re...,"spacewar,spaceopera,military",Animation,/brrgSFtcymZWaXl5a23GJRWdOSY.jpg
20998,21070,21070,24080,You Stupid Man,An actress dumps her boyfriend when she gets a...,"lovetriangle,director,break-up,ex-boyfriendex-...","Comedy,Romance",/vNfx5MBXkeqZKOW6Wx9W5kiNdSL.jpg
20999,21071,21071,1363,The Hi-Lo Country,An intimate story of the enduring bond of frie...,"pearlharbor,cowboy,pickuptruck,horseridingacci...","Drama,Romance,Western",/m73KqOLXf9ZvPVCWS5dz5Hv7yQF.jpg

In [20]:
df.shape

(21000, 8)

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21000 entries, 0 to 20999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   21000 non-null  int64
 1   index        21000 non-null  int64
 2   id           21000 non-null  int64
 3   title        21000 non-null  str
 4   overview     21000 non-null  str
 5   keywords     18535 non-null  str
 6   genres       20993 non-null  str
 7   poster_path  21000 non-null  str
dtypes: int64(3), str(5)
memory usage: 1.3 MB

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
df.isnull().sum()

Unnamed: 0        0
index             0
id                0
title             0
overview          0
keywords       2465
genres            7
poster_path       0
dtype: int64

In [24]:
df.drop(columns=["Unnamed: 0","index"],inplace=True)

In [25]:
df.head()

,id,title,overview,keywords,genres,poster_path
0,27205,Inception,"Cobb, a skilled thief who commits corporate es...","rescue,mission,dream,airplane,paris,france,vir...","Action,ScienceFiction,Adventure",/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg
1,157336,Interstellar,The adventures of a group of explorers who mak...,"rescue,future,spacecraft,raceagainsttime,artif...","Adventure,Drama,ScienceFiction",/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg
2,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,"joker,sadism,chaos,secretidentity,crimefighter...","Drama,Action,Crime,Thriller",/qJ2tW6WMUDux911r6m7haRef0WH.jpg
3,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","future,society,cultureclash,spacetravel,spacew...","Action,Adventure,Fantasy,ScienceFiction",/kyeqWdyUXW608qlYkRqosgbbJyK.jpg
4,24428,The Avengers,When an unexpected enemy emerges and threatens...,"newyorkcity,superhero,shield,basedoncomic,alie...","ScienceFiction,Action,Adventure",/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg

In [26]:
df.describe(include='all')

,id,title,overview,keywords,genres,poster_path
count,2.100000e+04,21000,21000,18535,20993,21000
unique,NaN,19934,20993,17678,3306,21000
top,NaN,The Return,Wilbur the pig is scared of the end of the sea...,womandirector,Comedy,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg
freq,NaN,6,2,111,1647,1
mean,2.065386e+05,NaN,NaN,NaN,NaN,NaN
std,2.607422e+05,NaN,NaN,NaN,NaN,NaN
min,2.000000e+00,NaN,NaN,NaN,NaN,NaN
25%,1.391975e+04,NaN,NaN,NaN,NaN,NaN
50%,4.906750e+04,NaN,NaN,NaN,NaN,NaN
75%,3.762400e+05,NaN,NaN,NaN,NaN,NaN
max,1.181678e+06,NaN,NaN,NaN,NaN,NaN

In [27]:
df.describe(include=[object])

C:\Users\srika\AppData\Local\Temp\ipykernel_25824\419507111.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include=[object])

,title,overview,keywords,genres,poster_path
count,21000,21000,18535,20993,21000
unique,19934,20993,17678,3306,21000
top,The Return,Wilbur the pig is scared of the end of the sea...,womandirector,Comedy,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg
freq,6,2,111,1647,1

In [28]:
df['tags']=df['overview']+df['keywords']+df['genres']

In [29]:
df['tags']

0        Cobb, a skilled thief who commits corporate es...
1        The adventures of a group of explorers who mak...
2        Batman raises the stakes in his war on crime. ...
3        In the 22nd century, a paraplegic Marine is di...
4        When an unexpected enemy emerges and threatens...
                               ...
20995    Popular TV anchorwoman & late night DJ Ko Sun-...
20996                                                  NaN
20997    The story focuses on the exploits of rivals Re...
20998    An actress dumps her boyfriend when she gets a...
20999    An intimate story of the enduring bond of frie...
Name: tags, Length: 21000, dtype: str

In [30]:
df.isnull().sum()

id                0
title             0
overview          0
keywords       2465
genres            7
poster_path       0
tags           2468
dtype: int64

In [31]:
df['tags']=df['overview']+df['keywords'].fillna('')+df['genres'].fillna('')

In [32]:
df.isnull().sum()

id                0
title             0
overview          0
keywords       2465
genres            7
poster_path       0
tags              0
dtype: int64

### Text Preprocessing

In [33]:
df['tags']=df['tags'].apply(lambda x:x.lower())

In [34]:
df['tags']

0        cobb, a skilled thief who commits corporate es...
1        the adventures of a group of explorers who mak...
2        batman raises the stakes in his war on crime. ...
3        in the 22nd century, a paraplegic marine is di...
4        when an unexpected enemy emerges and threatens...
                               ...
20995    popular tv anchorwoman & late night dj ko sun-...
20996    two friends lose their jobs, then part bitterl...
20997    the story focuses on the exploits of rivals re...
20998    an actress dumps her boyfriend when she gets a...
20999    an intimate story of the enduring bond of frie...
Name: tags, Length: 21000, dtype: str

In [35]:
#pip install nltk

In [36]:
from nltk.stem.porter import PorterStemmer

In [37]:
ps=PorterStemmer()

In [38]:
ps.stem('running')

'run'

In [39]:
def stemming(word):
    y=[]
    for i in word.split():
        y.append(ps.stem(i))
    return ' '.join(y)

In [40]:
df['tags'].iloc[0]

'cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious.rescue,mission,dream,airplane,paris,france,virtualreality,kidnapping,philosophy,spy,allegory,manipulation,carcrash,heist,memory,architecture,losangeles,california,dreamworld,subconsciousaction,sciencefiction,adventure'

In [41]:
df['tags']=df['tags'].apply(stemming)

In [42]:
df['tags'].iloc[0]

'cobb, a skill thief who commit corpor espionag by infiltr the subconsci of hi target is offer a chanc to regain hi old life as payment for a task consid to be impossible: "inception", the implant of anoth person\' idea into a target\' subconscious.rescue,mission,dream,airplane,paris,france,virtualreality,kidnapping,philosophy,spy,allegory,manipulation,carcrash,heist,memory,architecture,losangeles,california,dreamworld,subconsciousaction,sciencefiction,adventur'

In [43]:
from sklearn.feature_extraction.text import CountVectorizer

In [44]:
cv=CountVectorizer(max_features=2000,stop_words='english')

In [45]:
vector=cv.fit_transform(df['tags'])

In [46]:
vector.shape

(21000, 2000)

In [47]:
cv.get_feature_names_out().tolist()

['000',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '1920s',
 '1930s',
 '1940s',
 '1950s',
 '1960s',
 '1970s',
 '1980',
 '1980s',
 '1990s',
 '19th',
 '19thcentury',
 '20',
 '30',
 '40',
 'abandon',
 'abduct',
 'abil',
 'abl',
 'aboard',
 'abus',
 'accept',
 'accid',
 'accident',
 'accompani',
 'account',
 'accus',
 'achiev',
 'act',
 'action',
 'actionhero',
 'activ',
 'actor',
 'actress',
 'actual',
 'adam',
 'adapt',
 'addict',
 'adopt',
 'adoption',
 'adult',
 'adultanimation',
 'adultery',
 'advanc',
 'adventur',
 'adventure',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'aftercreditsstinger',
 'aftermath',
 'ag',
 'age',
 'agent',
 'ago',
 'agre',
 'aid',
 'air',
 'airplane',
 'airport',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alex',
 'alic',
 'alien',
 'alieninvasion',
 'aliv',
 'alive',
 'alli',
 'allow',
 'alon',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'ambiti',
 'america',
 'american',
 'amnesia',
 'ancient',
 'android',
 'angel',
 'angeles',
 'anger',
 'ani',
 'anim',
 'animal',
 'animalattack',
 'animation',
 'anime',
 'animeanimation',
 'ann',
 'anna',
 'annual',
 'anoth',
 'answer',
 'anthology',
 'anthropomorphism',
 'anti',
 'anyon',
 'anyth',
 'apart',
 'apartment',
 'apocalypse',
 'apocalypticfuture',
 'appear',
 'approach',
 'architect',
 'area',
 'argentina',
 'arizona',
 'arm',
 'armi',
 'army',
 'arrang',
 'arrest',
 'arriv',
 'art',
 'arthur',
 'artificialintelligence',
 'artist',
 'ask',
 'aspir',
 'assassin',
 'assassination',
 'assault',
 'assign',
 'assist',
 'assum',
 'astronaut',
 'asylum',
 'attack',
 'attempt',
 'attend',
 'attent',
 'attorney',
 'attract',
 'aunt',
 'australia',
 'author',
 'aveng',
 'avoid',
 'await',
 'awaken',
 'award',
 'away',
 'babi',
 'baby',
 'bachelor',
 'bad',
 'balanc',
 'ball',
 'ballet',
 'band',
 'bank',
 'bankrobbery',
 'bar',
 'bare',
 'baron',
 'base',
 'basedonchildren',
 'basedoncomic',
 'basedonmanga',
 'basedonmemoirorautobiography',
 'basedonnovelorbook',
 'basedonplayormusical',
 'basedonshortstory',
 'basedontruestory',
 'basedonvideogame',
 'basement',
 'batman',
 'battl',
 'battle',
 'beach',
 'bear',
 'beast',
 'beauti',
 'becam',
 'becaus',
 'becom',
 'bed',
 'befor',
 'befriend',
 'begin',
 'behavior',
 'believ',
 'belong',
 'belov',
 'ben',
 'berlin',
 'best',
 'bestfriend',
 'bet',
 'betray',
 'betrayal',
 'better',
 'big',
 'biggest',
 'billi',
 'biography',
 'birth',
 'birthday',
 'bit',
 'bizarr',
 'black',
 'blackandwhite',
 'blackmail',
 'blind',
 'blood',
 'bloodi',
 'blue',
 'board',
 'boat',
 'bob',
 'bodi',
 'body',
 'bodyguard',
 'bomb',
 'bond',
 'book',
 'border',
 'bore',
 'born',
 'boss',
 'boston',
 'bound',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'brain',
 'brave',
 'break',
 'bride',
 'brilliant',
 'bring',
 'britain',
 'british',
 'broken',
 'brooklyn',
 'brother',
 'brothers',
 'brought',
 'brutal',
 'brutality',
 'buddi',
 'build',
 'building',
 'built',
 'bulli',
 'bullying',
 'buri',
 'burn',
 'busi',
 'business',
 'businessman',
 'buy',
 'cabin',
 'california',
 'camera',
 'camp',
 'campaign',
 'canada',
 'cancer',
 'cannibal',
 'captain',
 'captiv',
 'captur',
 'car',
 'caraccident',
 'carcrash',
 'care',
 'career',
 'carri',
 'cartoon',
 'case',
 'cash',
 'casino',
 'cast',
 'castl',
 'castle',
 'cat',
 'catch',
 'caught',
 'caus',
 'cave',
 'celebr',
 'celebrity',
 'cell',
 'center',
 'centuri',
 'century',
 'certain',
 'chain',
 'challeng',
 'champion',
 'chanc',
 'chang',
 'chao',
 'chaos',
 'charact',
 'charg',
 'charl',
 'charli',
 'charm',
 'chase',
 'cheat',
 'chef',
 'chicago',
 'chief',
 'child',
 'childabuse',
 'childhood',
 'children',
 'china',
 'chines',
 'choic',
 'choos',
 'chosen',
 'christian',
 'christianity',
 'christma',
 'christmas',
 'chronicl',
 'church',
 'cia',
 'citi',
 'city',
 'civil',
 'claim',
 'clan',
 'clash',
 'class',
 'classic',
 'clean',
 'clear',
 'client',
 'clock',
 'close',
 'closer',
 'clown',
 'club',
 'clue',
 'coach',
 'coast',
 'cocaine',
 'code',
 'cold',
 'coldwar',
 'colleagu',
 'collect',
 'colleg',
 'college',
 'color',
 'coma',
 'combat',
 'come',
 'comedi',
 'comedian',
 'comedy',
 'comfort',
 'comic',
 'comingofage',
 'command',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'comput',
 'computer',
 'concern',
 'concert',
 'conflict',
 'confront',
 'connect',
 'consequ',
 'consequences',
 'consid',
 'conspiraci',
 'conspiracy',
 'contact',
 'contain',
 'contest',
 'continu',
 'contract',
 'control',
 'convict',
 'convinc',
 'cook',
 'cop',
 'cope',
 'corpor',
 'corps',
 'corrupt',
 'corruption',
 'cost',
 'count',
 'countri',
 'country',
 'countryside',
 'coupl',
 'couple',
 'courag',
 'cours',
 'court',
 'cousin',
 'cover',
 'cowboy',
 'crack',
 'crash',
 'crazi',
 'creat',
 'creatur',
 'creature',
 'crew',
 'crim',
 'crime',
 'crimin',
 'criminal',
 'crisi',
 'crisis',
 'crook',
 'cross',
 'cruel',
 'crush',
 'cult',
 'cultur',
 'cure',
 'current',
 'curs',
 'curse',
 'cut',
 'cyberpunk',
 'cyborg',
 'dad',
 'daili',
 'danc',
 'dance',
 'dancer',
 'dancing',
 'danger',
 'daniel',
 'danni',
 'dare',
 'dark',
 'darkcomedy',
 'date',
 'daughter',
 'david',
 'day',
 'days',
 'dead',
 'deadli',
 'deaf',
 'deal',
 'dealer',
 'death',
 'debt',
 'decad',
 'deceas',
 'deception',
 'decid',
 'decis',
 'dedic',
 'deep',
 'defeat',
 'defend',
 'deliv',
 'demand',
 'demon',
 'depart',
 'depression',
 'descend',
 'desert',
 'design',
 'desir',
 'desper',
 'despit',
 'destin',
 'destroy',
 'destruct',
 'destruction',
 'detect',
 'detective',
 'determin',
 'detroit',
 'devast',
 'develop',
 'devil',
 'devot',
 'diamond',
 'did',
 'didn',
 'die',
 'dies',
 'differ',
 'difficult',
 'dinner',
 'dinosaur',
 'direct',
 'director',
 'disappear',
 'disappearance',
 'disaster',
 'discov',
 'discoveri',
 'discovery',
 'distant',
 'district',
 'disturb',
 'divorc',
 'divorce',
 'doctor',
 'document',
 'documentari',
 'documentary',
 'doe',
 'doesn',
 'dog',
 'doll',
 'dollar',
 'don',
 'door',
 'doubl',
 'dr',
 'drag',
 'dragon',
 'drama',
 'draw',
 'drawn',
 'dream',
 'dreams',
 'dress',
 'drifter',
 'drink',
 'drive',
 'driven',
 'driver',
 'drop',
 'drug',
 'drugaddiction',
 'drugdealer',
 'drugs',
 'dump',
 'duo',
 'dure',
 'duringcreditsstinger',
 'duti',
 'dyinganddeath',
 'dysfunctionalfamily',
 'dystopia',
 'earli',
 'earlier',
 'earn',
 'earth',
 'easi',
 'east',
 'eat',
 'eccentr',
 'eddi',
 'effect',
 'effort',
 'egypt',
 'elderli',
 'elit',
 'els',
 'embark',
 'emerg',
 'emot',
 'emperor',
 'employ',
 'employe',
 'encount',
 'end',
 'endur',
 'enemi',
 'enemy',
 'engag',
 'engin',
 'england',
 'english',
 'enigmat',
 'enjoy',
 'enlist',
 'enter',
 'entertain',
 'entir',
 'epic',
 'era',
 'eroticism',
 'escap',
 'escape',
 'especi',
 'espionage',
 'establish',
 'estat',
 'estrang',
 'europe',
 'european',
 'eve',
 'event',
 'events',
 'eventu',
 'everi',
 'everyon',
 'everyth',
 'evid',
 'evil',
 'ex',
 'exact',
 'exactli',
 'examin',
 'exchang',
 'excit',
 'execut',
 'exist',
 'existence',
 'expect',
 'experi',
 'experienc',
 'experiment',
 'expert',
 'explor',
 'explos',
 'explosion',
 'expos',
 'extramaritalaffair',
 'extraordinari',
 'extrem',
 'eye',
 'face',
 'fact',
 'factori',
 'fail',
 'fairi',
 'fairytale',
 'faith',
 'fake',
 'fall',
 'fallen',
 'fallinginlove',
 'fame',
 'famili',
 'family',
 'familyrelationships',
 'famou',
 'fan',
 'fantasi',
 'fantasy',
 'far',
 'farm',
 'farmer',
 'fashion',
 'fast',
 'fatal',
 'fate',
 'father',
 'fatherdaughterrelationship',
 'fathersonrelationship',
 'favorit',
 'fbi',
 'fear',
 'featur',
 'feder',
 'feel',
 'fellow',
 'femal',
 'femalefriendship',
 'femaleprotagonist',
 'fiancé',
 'fiction',
 'field',
 'fierc',
 'fight',
 'fighter',
 'figur',
 'film',
 'filmmak',
 'filmnoir',
 'final',
 'financi',
 'finish',
 'firm',
 'fish',
 'fit',
 'flashback',
 'flee',
 'fli',
 'flight',
 'florida',
 'focus',
 'follow',
 'food',
 'foot',
 'footag',
 'footbal',
 'football',
 'forbiddenlove',
 'forc',
 'foreign',
 'forest',
 'forev',
 'forever',
 'form',
 'fortun',
 'foundfootage',
 'frame',
 'franc',
 'france',
 'francisco',
 'frank',
 'frankenstein',
 'fred',
 'free',
 'freedom',
 'french',
 'friend',
 'friends',
 'friendship',
 'fulfil',
 'fun',
 'funeral',
 'futur',
 'future',
 'gain',
 'gambling',
 'game',
 'games',
 'gang',
 'gangster',
 'garden',
 'gather',
 'gay',
 'gaytheme',
 'gaythemedrama',
 'gener',
 'georg',
 'german',
 'germany',
 'ghetto',
 'ghost',
 'giant',
 'gift',
 'girl',
 'girlfriend',
 'girls',
 'given',
 'global',
 'goal',
 'god',
 'goe',
 'gold',
 'gone',
 'good',
 'gore',
 'got',
 'govern',
 'government',
 'gradual',
 'graduat',
 'grand',
 'grandfather',
 'grant',
 'grave',
 'great',
 'greatest',
 'greed',
 'green',
 'grief',
 'ground',
 'group',
 'grow',
 'grown',
 'gruesom',
 'guard',
 'guest',
 'guid',
 'guilt',
 'gun',
 'gunfight',
 'guy',
 'ha',
 'hacker',
 'hair',
 'half',
 'hall',
 'halloween',
 'hallucination',
 'hand',
 'handsom',
 'hang',
 'happen',
 'happi',
 'hard',
 'harri',
 'hatch',
 'haunt',
 'hauntedhouse',
 'havoc',
 'head',
 'health',
 'hear',
 'heart',
 'heir',
 'heist',
 'held',
 'helicopter',
 'hell',
 'help',
 'henri',
 'hero',
 'heroin',
 'hi',
 'hidden',
 'hide',
 'high',
 'highli',
 'highschool',
 'hilari',
 'hill',
 'hip',
 'hire',
 'histori',
 'history',
 'hit',
 'hitman',
 'hold',
 'hole',
 'holiday',
 'hollywood',
 'home',
 'homeless',
 'hometown',
 'homophobia',
 'hong',
 'honor',
 'hood',
 'hop',
 'hope',
 'horribl',
 'horrif',
 'horrifi',
 'horror',
 'horse',
 'hospit',
 'hospital',
 'host',
 'hostag',
 'hostage',
 'hot',
 'hotel',
 'hour',
 'hous',
 'house',
 'huge',
 'human',
 'humanity',
 'hundr',
 'hunt',
 'hunter',
 'husband',
 'husbandwiferelationship',
 'ice',
 'icon',
 'idea',
 'ident',
 'identity',
 'ii',
 'ill',
 'illeg',
 'illinois',
 'illness',
 'imag',
 'imagin',
 'immedi',
 'immigr',
 'import',
 'imposs',
 'imprison',
 'incest',
 'incid',
 'includ',
 'increasingli',
 'incred',
 'independ',
 'india',
 'indian',
 'infam',
 'infidelity',
 'infiltr',
 'influenc',
 'inform',
 'inhabit',
 'inherit',
 'inheritance',
 'initi',
 'inner',
 'innoc',
 'insanity',
 'insid',
 'inspector',
 'inspir',
 'instead',
 'intellig',
 'intend',
 'intens',
 'intent',
 'intern',
 'internet',
 'interview',
 'intim',
 'introduc',
 'invad',
 'invent',
 'inventor',
 'investig',
 'investigation',
 'invit',
 'involv',
 'ireland',
 'irish',
 'island',
 'isn',
 'isol',
 'isolation',
 'issu',
 'itali',
 'italian',
 'italy',
 'jack',
 'jail',
 'jake',
 'jame',
 'jane',
 'japan',
 'japanes',
 'jealousy',
 'jean',
 'jess',
 'jewish',
 'jim',
 'jimmi',
 'job',
 'joe',
 'john',
 'johnni',
 'join',
 'journalist',
 'journey',
 'joy',
 'jungl',
 'jungle',
 'just',
 'justic',
 'justice',
 'kate',
 'kevin',
 'key',
 'kick',
 'kid',
 'kidnap',
 'kidnapping',
 'kids',
 'kill',
 'killed',
 'killer',
 'kind',
 'king',
 'kingdom',
 'kiss',
 'knew',
 'knife',
 'knight',
 'know',
 'known',
 'kong',
 'korean',
 ...]

### Calculate Similarity Score

In [48]:
from sklearn.metrics.pairwise import cosine_similarity

In [49]:
similarity=cosine_similarity(vector)

In [50]:
similarity[0]

array([1.        , 0.06003002, 0.05014122, ..., 0.        , 0.07352146,
       0.        ], shape=(21000,))

In [51]:
similaritydf=pd.DataFrame(similarity,index=df['title'],columns=df['title'])

In [52]:
similaritydf.loc['Avatar'].sort_values(ascending=False)[1:5]

title
Independence Day                       0.364646
Space Chimps 2: Zartog Strikes Back    0.341394
Skylines                               0.336336
King Shakir Recycle                    0.326860
Name: Avatar, dtype: float64

In [53]:
similarity[0]

array([1.        , 0.06003002, 0.05014122, ..., 0.        , 0.07352146,
       0.        ], shape=(21000,))

In [54]:
enumerate(similarity[0])

In [55]:
list(enumerate(similarity[0]))

[(0, np.float64(0.9999999999999993)),
 (1, np.float64(0.06003002251876642)),
 (2, np.float64(0.050141221056390024)),
 (3, np.float64(0.03224129401095805)),
 (4, np.float64(0.0644825880219161)),
 (5, np.float64(0.1389425035941821)),
 (6, np.float64(0.09394227846020416)),
 (7, np.float64(0.0)),
 (8, np.float64(0.14704292441876154)),
 (9, np.float64(0.1677890138035061)),
 (10, np.float64(0.12535305264097507)),
 (11, np.float64(0.21312067103033536)),
 (12, np.float64(0.08489527199560176)),
 (13, np.float64(0.09672388203287416)),
 (14, np.float64(0.2122381799890044)),
 (15, np.float64(0.027788500718836418)),
 (16, np.float64(0.029526929767874632)),
 (17, np.float64(0.04474373701426829)),
 (18, np.float64(0.055577001437672836)),
 (19, np.float64(0.09802861627917438)),
 (20, np.float64(0.0)),
 (21, np.float64(0.059053859535749265)),
 (22, np.float64(0.03224129401095805)),
 (23, np.float64(0.05723638070321425)),
 (24, np.float64(0.0)),
 (25, np.float64(0.0)),
 (26, np.float64(0.04559607525875532)),
 (27, np.float64(0.13678822577626598)),
 (28, np.float64(0.10514994558491725)),
 (29, np.float64(0.06003002251876642)),
 (30, np.float64(0.09913631941932194)),
 (31, np.float64(0.041424651066746664)),
 (32, np.float64(0.1823843010350213)),
 (33, np.float64(0.08718572905786445)),
 (34, np.float64(0.039872611141445)),
 (35, np.float64(0.03224129401095805)),
 (36, np.float64(0.0)),
 (37, np.float64(0.036760731104690386)),
 (38, np.float64(0.0)),
 (39, np.float64(0.10959932487023819)),
 (40, np.float64(0.2256354947537551)),
 (41, np.float64(0.1389425035941821)),
 (42, np.float64(0.07009996372327816)),
 (43, np.float64(0.12119654139092992)),
 (44, np.float64(0.03163859985841663)),
 (45, np.float64(0.09491579957524991)),
 (46, np.float64(0.047457899787624956)),
 (47, np.float64(0.0)),
 (48, np.float64(0.03224129401095805)),
 (49, np.float64(0.0)),
 (50, np.float64(0.0)),
 (51, np.float64(0.24002133617819926)),
 (52, np.float64(0.2790404591875126)),
 (53, np.float64(0.1316245316231641)),
 (54, np.float64(0.13513513513513514)),
 (55, np.float64(0.19827263883864388)),
 (56, np.float64(0.1643989873053573)),
 (57, np.float64(0.04393747751637468)),
 (58, np.float64(0.15404884978892905)),
 (59, np.float64(0.11510231387903269)),
 (60, np.float64(0.056388387443460086)),
 (61, np.float64(0.16120647005479025)),
 (62, np.float64(0.028618190351607124)),
 (63, np.float64(0.0)),
 (64, np.float64(0.0)),
 (65, np.float64(0.0)),
 (66, np.float64(0.20518233866439894)),
 (67, np.float64(0.0)),
 (68, np.float64(0.0)),
 (69, np.float64(0.042098266797411445)),
 (70, np.float64(0.07174960033341753)),
 (71, np.float64(0.09863939238321438)),
 (72, np.float64(0.09320546490018)),
 (73, np.float64(0.17170914210964275)),
 (74, np.float64(0.03163859985841663)),
 (75, np.float64(0.0)),
 (76, np.float64(0.2102998911698345)),
 (77, np.float64(0.02567480829815484)),
 (78, np.float64(0.2990445835608375)),
 (79, np.float64(0.1643989873053573)),
 (80, np.float64(0.03224129401095805)),
 (81, np.float64(0.0)),
 (82, np.float64(0.09863939238321438)),
 (83, np.float64(0.2442250043490654)),
 (84, np.float64(0.16916516233038026)),
 (85, np.float64(0.07749842582921286)),
 (86, np.float64(0.059053859535749265)),
 (87, np.float64(0.0)),
 (88, np.float64(0.0)),
 (89, np.float64(0.0)),
 (90, np.float64(0.08458258116519013)),
 (91, np.float64(0.07897471897389846)),
 (92, np.float64(0.0)),
 (93, np.float64(0.0)),
 (94, np.float64(0.09158437663089952)),
 (95, np.float64(0.0)),
 (96, np.float64(0.0)),
 (97, np.float64(0.03163859985841663)),
 (98, np.float64(0.2256354947537551)),
 (99, np.float64(0.06575959492214292)),
 (100, np.float64(0.09004503377814962)),
 (101, np.float64(0.09394227846020416)),
 (102, np.float64(0.056388387443460086)),
 (103, np.float64(0.03163859985841663)),
 (104, np.float64(0.0)),
 (105, np.float64(0.0533380747062665)),
 (106, np.float64(0.050734628943184104)),
 (107, np.float64(0.0)),
 (108, np.float64(0.03163859985841663)),
 (109, np.float64(0.07352146220938077)),
 (110, np.float64(0.028618190351607124)),
 (111, np.float64(0.11624763874381927)),
 (112, np.float64(0.0)),
 (113, np.float64(0.0885807893036239)),
 (114, np.float64(0.03106848830006)),
 (115, np.float64(0.02632490632463282)),
 (116, np.float64(0.09158437663089952)),
 (117, np.float64(0.027399831217559546)),
 (118, np.float64(0.07974522228289)),
 (119, np.float64(0.059053859535749265)),
 (120, np.float64(0.10514994558491725)),
 (121, np.float64(0.058123819371909635)),
 (122, np.float64(0.028618190351607124)),
 (123, np.float64(0.1061190899945022)),
 (124, np.float64(0.0)),
 (125, np.float64(0.08219949365267865)),
 (126, np.float64(0.12392039927415242)),
 (127, np.float64(0.14763464883937316)),
 (128, np.float64(0.036760731104690386)),
 (129, np.float64(0.0)),
 (130, np.float64(0.0)),
 (131, np.float64(0.18009006755629928)),
 (132, np.float64(0.13678822577626598)),
 (133, np.float64(0.14704292441876154)),
 (134, np.float64(0.0)),
 (135, np.float64(0.08489527199560176)),
 (136, np.float64(0.02567480829815484)),
 (137, np.float64(0.09802861627917438)),
 (138, np.float64(0.0)),
 (139, np.float64(0.2071841649822589)),
 (140, np.float64(0.2657423679108717)),
 (141, np.float64(0.10397504898200727)),
 (142, np.float64(0.0)),
 (143, np.float64(0.05479966243511909)),
 (144, np.float64(0.0)),
 (145, np.float64(0.11510231387903269)),
 (146, np.float64(0.03874921291460643)),
 (147, np.float64(0.0)),
 (148, np.float64(0.0533380747062665)),
 (149, np.float64(0.0)),
 (150, np.float64(0.0)),
 (151, np.float64(0.0)),
 (152, np.float64(0.08787495503274936)),
 (153, np.float64(0.1139901881468883)),
 (154, np.float64(0.08000711205939975)),
 (155, np.float64(0.0)),
 (156, np.float64(0.09592022754223367)),
 (157, np.float64(0.0)),
 (158, np.float64(0.11624763874381927)),
 (159, np.float64(0.18599622199011084)),
 (160, np.float64(0.0)),
 (161, np.float64(0.0)),
 (162, np.float64(0.056388387443460086)),
 (163, np.float64(0.055577001437672836)),
 (164, np.float64(0.10762440050012628)),
 (165, np.float64(0.10397504898200727)),
 (166, np.float64(0.0)),
 (167, np.float64(0.0644825880219161)),
 (168, np.float64(0.0199363055707225)),
 (169, np.float64(0.16967515794730187)),
 (170, np.float64(0.06070834938872646)),
 (171, np.float64(0.0)),
 (172, np.float64(0.0)),
 (173, np.float64(0.0)),
 (174, np.float64(0.10701462561817378)),
 (175, np.float64(0.059053859535749265)),
 (176, np.float64(0.03355780276070122)),
 (177, np.float64(0.0)),
 (178, np.float64(0.06575959492214292)),
 (179, np.float64(0.0)),
 (180, np.float64(0.10959932487023819)),
 (181, np.float64(0.19771864882368606)),
 (182, np.float64(0.09863939238321438)),
 (183, np.float64(0.16673100431301852)),
 (184, np.float64(0.03427955850955305)),
 (185, np.float64(0.2650854018430104)),
 (186, np.float64(0.09299811099505542)),
 (187, np.float64(0.1342312110428049)),
 (188, np.float64(0.0)),
 (189, np.float64(0.0)),
 (190, np.float64(0.059053859535749265)),
 (191, np.float64(0.12253577034896797)),
 (192, np.float64(0.24609055357847556)),
 (193, np.float64(0.05405405405405406)),
 (194, np.float64(0.08718572905786445)),
 (195, np.float64(0.14704292441876157)),
 (196, np.float64(0.0)),
 (197, np.float64(0.15660307954993902)),
 (198, np.float64(0.04901430813958719)),
 (199, np.float64(0.024784079854830485)),
 (200, np.float64(0.07218053273850816)),
 (201, np.float64(0.06575959492214292)),
 (202, np.float64(0.21029989116983447)),
 (203, np.float64(0.06327719971683327)),
 (204, np.float64(0.0)),
 (205, np.float64(0.0)),
 (206, np.float64(0.0)),
 (207, np.float64(0.0)),
 (208, np.float64(0.0)),
 (209, np.float64(0.1311450235388945)),
 (210, np.float64(0.0)),
 (211, np.float64(0.10067340828210367)),
 (212, np.float64(0.11810771907149853)),
 (213, np.float64(0.024507154069793594)),
 (214, np.float64(0.04474373701426829)),
 (215, np.float64(0.0)),
 (216, np.float64(0.1526406277181659)),
 (217, np.float64(0.0)),
 (218, np.float64(0.0)),
 (219, np.float64(0.07897471897389846)),
 (220, np.float64(0.15042366316917005)),
 (221, np.float64(0.09695723311274393)),
 (222, np.float64(0.025993762245501817)),
 (223, np.float64(0.06575959492214292)),
 (224, np.float64(0.059053859535749265)),
 (225, np.float64(0.10146925788636821)),
 (226, np.float64(0.07798128673650545)),
 (227, np.float64(0.12427395320024)),
 (228, np.float64(0.0)),
 (229, np.float64(0.05479966243511909)),
 (230, np.float64(0.050141221056390024)),
 (231, np.float64(0.03874921291460643)),
 (232, np.float64(0.2632490632463282)),
 (233, np.float64(0.03287979746107146)),
 (234, np.float64(0.0885807893036239)),
 (235, np.float64(0.11389895949029986)),
 (236, np.float64(0.23249527748763857)),
 (237, np.float64(0.14165281524036175)),
 (238, np.float64(0.0)),
 (239, np.float64(0.0)),
 (240, np.float64(0.055577001437672836)),
 (241, np.float64(0.21919864974047637)),
 (242, np.float64(0.03771571432023571)),
 (243, np.float64(0.04433510985214727)),
 (244, np.float64(0.0)),
 (245, np.float64(0.0)),
 (246, np.float64(0.022371868507134143)),
 (247, np.float64(0.06213697660012)),
 (248, np.float64(0.0)),
 (249, np.float64(0.0)),
 (250, np.float64(0.06213697660012)),
 (251, np.float64(0.03106848830006)),
 (252, np.float64(0.2279803762937766)),
 (253, np.float64(0.18668326147193276)),
 (254, np.float64(0.07009996372327816)),
 (255, np.float64(0.1289651760438322)),
 (256, np.float64(0.06003002251876642)),
 (257, np.float64(0.10067340828210367)),
 (258, np.float64(0.0)),
 (259, np.float64(0.148916158209988)),
 (260, np.float64(0.14097096860865022)),
 (261, np.float64(0.08458258116519013)),
 (262, np.float64(0.18494886071852695)),
 (263, np.float64(0.14763464883937316)),
 (264, np.float64(0.13949716649258315)),
 (265, np.float64(0.0)),
 (266, np.float64(0.1898315991504998)),
 (267, np.float64(0.09913631941932194)),
 (268, np.float64(0.1454358496691159)),
 (269, np.float64(0.25070610528195014)),
 (270, np.float64(0.08219949365267865)),
 (271, np.float64(0.18983159915049982)),
 (272, np.float64(0.0)),
 (273, np.float64(0.18790823039834775)),
 (274, np.float64(0.03163859985841663)),
 (275, np.float64(0.13181243254912406)),
 (276, np.float64(0.0)),
 (277, np.float64(0.19827263883864388)),
 (278, np.float64(0.03287979746107146)),
 (279, np.float64(0.07897471897389846)),
 (280, np.float64(0.03001501125938321)),
 (281, np.float64(0.0)),
 (282, np.float64(0.08489527199560176)),
 (283, np.float64(0.0)),
 (284, np.float64(0.09863939238321438)),
 (285, np.float64(0.16916516233038026)),
 (286, np.float64(0.07352146220938077)),
 (287, np.float64(0.15949044456578)),
 (288, np.float64(0.0)),
 (289, np.float64(0.14543584966911588)),
 (290, np.float64(0.0)),
 (291, np.float64(0.03287979746107146)),
 (292, np.float64(0.1485667259923031)),
 (293, np.float64(0.08718572905786445)),
 (294, np.float64(0.08458258116519013)),
 (295, np.float64(0.0)),
 (296, np.float64(0.02279803762937766)),
 (297, np.float64(0.07543142864047142)),
 (298, np.float64(0.06367145399670132)),
 (299, np.float64(0.14091341769030624)),
 (300, np.float64(0.06105625108726635)),
 (301, np.float64(0.05479966243511909)),
 (302, np.float64(0.039872611141445)),
 (303, np.float64(0.03163859985841663)),
 (304, np.float64(0.0)),
 (305, np.float64(0.04109974682633932)),
 (306, np.float64(0.13181243254912406)),
 (307, np.float64(0.08561170049453902)),
 (308, np.float64(0.03287979746107146)),
 (309, np.float64(0.09863939238321438)),
 (310, np.float64(0.05134961659630968)),
 (311, np.float64(0.07009996372327816)),
 (312, np.float64(0.09032775043542898)),
 (313, np.float64(0.036760731104690386)),
 (314, np.float64(0.12683657235796025)),
 (315, np.float64(0.17155007848855516)),
 (316, np.float64(0.0685591170191061)),
 (317, np.float64(0.13812277665483924)),
 (318, np.float64(0.08219949365267865)),
 (319, np.float64(0.15949044456578)),
 (320, np.float64(0.0)),
 (321, np.float64(0.09158437663089952)),
 (322, np.float64(0.05723638070321425)),
 (323, np.float64(0.0)),
 (324, np.float64(0.0863465783552691)),
 (325, np.float64(0.0)),
 (326, np.float64(0.1354916256531435)),
 (327, np.float64(0.10514994558491725)),
 (328, np.float64(0.06003002251876642)),
 (329, np.float64(0.0)),
 (330, np.float64(0.030528125543633176)),
 (331, np.float64(0.15499685165842572)),
 (332, np.float64(0.10810810810810811)),
 (333, np.float64(0.2029385157727364)),
 (334, np.float64(0.029526929767874632)),
 (335, np.float64(0.08787495503274936)),
 (336, np.float64(0.0)),
 (337, np.float64(0.0)),
 (338, np.float64(0.1342312110428049)),
 (339, np.float64(0.13949716649258312)),
 (340, np.float64(0.039872611141445)),
 (341, np.float64(0.2056773510573183)),
 (342, np.float64(0.03001501125938321)),
 (343, np.float64(0.2632490632463282)),
 (344, np.float64(0.02279803762937766)),
 (345, np.float64(0.0885807893036239)),
 (346, np.float64(0.06711560552140244)),
 (347, np.float64(0.10529962529853128)),
 (348, np.float64(0.0)),
 (349, np.float64(0.21010507881568247)),
 (350, np.float64(0.0)),
 (351, np.float64(0.0)),
 (352, np.float64(0.04901430813958719)),
 (353, np.float64(0.0)),
 (354, np.float64(0.0644825880219161)),
 (355, np.float64(0.15042366316917005)),
 (356, np.float64(0.04697113923010208)),
 (357, np.float64(0.09863939238321438)),
 (358, np.float64(0.03355780276070122)),
 (359, np.float64(0.19605723255834873)),
 (360, np.float64(0.08718572905786445)),
 (361, np.float64(0.17155007848855516)),
 (362, np.float64(0.03224129401095805)),
 (363, np.float64(0.15086285728094284)),
 (364, np.float64(0.10959932487023819)),
 (365, np.float64(0.09208185110322616)),
 (366, np.float64(0.0)),
 (367, np.float64(0.10397504898200727)),
 (368, np.float64(0.08489527199560176)),
 (369, np.float64(0.0)),
 (370, np.float64(0.0)),
 (371, np.float64(0.0)),
 (372, np.float64(0.08458258116519013)),
 (373, np.float64(0.0)),
 (374, np.float64(0.06711560552140244)),
 (375, np.float64(0.03771571432023571)),
 (376, np.float64(0.11624763874381927)),
 (377, np.float64(0.0)),
 (378, np.float64(0.050141221056390024)),
 (379, np.float64(0.08336550215650926)),
 (380, np.float64(0.0)),
 (381, np.float64(0.0)),
 (382, np.float64(0.07352146220938079)),
 (383, np.float64(0.0)),
 (384, np.float64(0.07974522228289)),
 (385, np.float64(0.0)),
 (386, np.float64(0.025993762245501817)),
 (387, np.float64(0.09119215051751065)),
 (388, np.float64(0.05134961659630968)),
 (389, np.float64(0.18857857160117855)),
 (390, np.float64(0.1606762634546782)),
 (391, np.float64(0.1186447494690624)),
 (392, np.float64(0.0)),
 (393, np.float64(0.0)),
 (394, np.float64(0.1559625734730109)),
 (395, np.float64(0.04109974682633932)),
 (396, np.float64(0.09394227846020416)),
 (397, np.float64(0.19727878476642874)),
 (398, np.float64(0.21137012653545936)),
 (399, np.float64(0.0)),
 (400, np.float64(0.0)),
 (401, np.float64(0.1342312110428049)),
 (402, np.float64(0.0)),
 (403, np.float64(0.0)),
 (404, np.float64(0.2324952774876386)),
 (405, np.float64(0.0)),
 (406, np.float64(0.0)),
 (407, np.float64(0.08489527199560176)),
 (408, np.float64(0.02632490632463282)),
 (409, np.float64(0.03504998186163908)),
 (410, np.float64(0.03427955850955305)),
 (411, np.float64(0.029061909685954818)),
 (412, np.float64(0.0)),
 (413, np.float64(0.0)),
 (414, np.float64(0.0644825880219161)),
 (415, np.float64(0.06105625108726635)),
 (416, np.float64(0.13678822577626595)),
 (417, np.float64(0.03224129401095805)),
 (418, np.float64(0.07543142864047142)),
 (419, np.float64(0.15794943794779692)),
 (420, np.float64(0.0)),
 (421, np.float64(0.0)),
 (422, np.float64(0.22555354977384034)),
 (423, np.float64(0.0)),
 (424, np.float64(0.0)),
 (425, np.float64(0.09158437663089952)),
 (426, np.float64(0.11314714296070713)),
 (427, np.float64(0.12683657235796025)),
 (428, np.float64(0.15404884978892902)),
 (429, np.float64(0.07352146220938077)),
 (430, np.float64(0.10514994558491725)),
 (431, np.float64(0.08219949365267865)),
 (432, np.float64(0.019374606457303215)),
 (433, np.float64(0.0)),
 (434, np.float64(0.11961783342433499)),
 (435, np.float64(0.039872611141445)),
 (436, np.float64(0.07352146220938077)),
 (437, np.float64(0.06213697660012)),
 (438, np.float64(0.059053859535749265)),
 (439, np.float64(0.06711560552140244)),
 (440, np.float64(0.0)),
 (441, np.float64(0.0885807893036239)),
 (442, np.float64(0.14763464883937316)),
 (443, np.float64(0.0)),
 (444, np.float64(0.0)),
 (445, np.float64(0.04109974682633932)),
 (446, np.float64(0.0)),
 (447, np.float64(0.03427955850955305)),
 (448, np.float64(0.2790404591875126)),
 (449, np.float64(0.036760731104690386)),
 (450, np.float64(0.03587480016670876)),
 (451, np.float64(0.1677890138035061)),
 (452, np.float64(0.18599622199011084)),
 (453, np.float64(0.11624763874381927)),
 (454, np.float64(0.02632490632463282)),
 (455, np.float64(0.1643989873053573)),
 (456, np.float64(0.17574991006549873)),
 (457, np.float64(0.1316245316231641)),
 (458, np.float64(0.0)),
 (459, np.float64(0.0)),
 (460, np.float64(0.0)),
 (461, np.float64(0.09158437663089952)),
 (462, np.float64(0.18065550087085797)),
 (463, np.float64(0.05405405405405406)),
 (464, np.float64(0.07543142864047142)),
 (465, np.float64(0.17574991006549873)),
 (466, np.float64(0.12655439943366653)),
 (467, np.float64(0.14019992744655632)),
 (468, np.float64(0.22581937608857244)),
 (469, np.float64(0.1526406277181659)),
 (470, np.float64(0.05479966243511909)),
 (471, np.float64(0.0)),
 (472, np.float64(0.0644825880219161)),
 (473, np.float64(0.0)),
 (474, np.float64(0.1252721535988985)),
 (475, np.float64(0.03874921291460643)),
 (476, np.float64(0.12006004503753284)),
 (477, np.float64(0.14704292441876154)),
 (478, np.float64(0.11810771907149853)),
 (479, np.float64(0.12655439943366653)),
 (480, np.float64(0.0)),
 (481, np.float64(0.0)),
 (482, np.float64(0.0)),
 (483, np.float64(0.0)),
 (484, np.float64(0.04559607525875532)),
 (485, np.float64(0.08585457105482137)),
 (486, np.float64(0.058123819371909635)),
 (487, np.float64(0.07974522228289)),
 (488, np.float64(0.07521183158458504)),
 (489, np.float64(0.0)),
 (490, np.float64(0.09913631941932194)),
 (491, np.float64(0.0)),
 (492, np.float64(0.0)),
 (493, np.float64(0.1553424415003)),
 (494, np.float64(0.08489527199560176)),
 (495, np.float64(0.0)),
 (496, np.float64(0.07174960033341753)),
 (497, np.float64(0.10514994558491725)),
 (498, np.float64(0.10514994558491725)),
 (499, np.float64(0.12329924047901797)),
 (500, np.float64(0.025993762245501817)),
 (501, np.float64(0.0)),
 (502, np.float64(0.059053859535749265)),
 (503, np.float64(0.14543584966911588)),
 (504, np.float64(0.05405405405405406)),
 (505, np.float64(0.09004503377814962)),
 (506, np.float64(0.03427955850955305)),
 (507, np.float64(0.08219949365267865)),
 (508, np.float64(0.050734628943184104)),
 (509, np.float64(0.08219949365267865)),
 (510, np.float64(0.07749842582921286)),
 (511, np.float64(0.047457899787624956)),
 (512, np.float64(0.05723638070321425)),
 (513, np.float64(0.0)),
 (514, np.float64(0.0)),
 (515, np.float64(0.0949157995752499)),
 (516, np.float64(0.1553424415003)),
 (517, np.float64(0.07352146220938077)),
 (518, np.float64(0.11961783342433499)),
 (519, np.float64(0.0)),
 (520, np.float64(0.1221125021745327)),
 (521, np.float64(0.0)),
 (522, np.float64(0.03587480016670876)),
 (523, np.float64(0.1841637022064523)),
 (524, np.float64(0.03355780276070122)),
 (525, np.float64(0.14349920066683505)),
 (526, np.float64(0.1221125021745327)),
 (527, np.float64(0.0)),
 (528, np.float64(0.0)),
 (529, np.float64(0.0)),
 (530, np.float64(0.0)),
 (531, np.float64(0.22147019900891643)),
 (532, np.float64(0.0)),
 (533, np.float64(0.23543217635998231)),
 (534, np.float64(0.05479966243511909)),
 (535, np.float64(0.08585457105482137)),
 (536, np.float64(0.04244763599780088)),
 (537, np.float64(0.20539846638523873)),
 (538, np.float64(0.11961783342433499)),
 (539, np.float64(0.22830583024432843)),
 (540, np.float64(0.03874921291460643)),
 (541, np.float64(0.0)),
 (542, np.float64(0.0)),
 (543, np.float64(0.039872611141445)),
 (544, np.float64(0.06213697660012)),
 (545, np.float64(0.14097096860865022)),
 (546, np.float64(0.07174960033341753)),

In [56]:
similarity

array([[1.        , 0.06003002, 0.05014122, ..., 0.        , 0.07352146,
        0.        ],
       [0.06003002, 1.        , 0.        , ..., 0.        , 0.04082483,
        0.0372678 ],
       [0.05014122, 0.        , 1.        , ..., 0.05391639, 0.03409972,
        0.06225728],
       ...,
       [0.        , 0.        , 0.05391639, ..., 1.        , 0.        ,
        0.07216878],
       [0.07352146, 0.04082483, 0.03409972, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.0372678 , 0.06225728, ..., 0.07216878, 0.        ,
        1.        ]], shape=(21000, 21000))

In [57]:
list(enumerate(similarity[0]))

[(0, np.float64(0.9999999999999993)),
 (1, np.float64(0.06003002251876642)),
 (2, np.float64(0.050141221056390024)),
 (3, np.float64(0.03224129401095805)),
 (4, np.float64(0.0644825880219161)),
 (5, np.float64(0.1389425035941821)),
 (6, np.float64(0.09394227846020416)),
 (7, np.float64(0.0)),
 (8, np.float64(0.14704292441876154)),
 (9, np.float64(0.1677890138035061)),
 (10, np.float64(0.12535305264097507)),
 (11, np.float64(0.21312067103033536)),
 (12, np.float64(0.08489527199560176)),
 (13, np.float64(0.09672388203287416)),
 (14, np.float64(0.2122381799890044)),
 (15, np.float64(0.027788500718836418)),
 (16, np.float64(0.029526929767874632)),
 (17, np.float64(0.04474373701426829)),
 (18, np.float64(0.055577001437672836)),
 (19, np.float64(0.09802861627917438)),
 (20, np.float64(0.0)),
 (21, np.float64(0.059053859535749265)),
 (22, np.float64(0.03224129401095805)),
 (23, np.float64(0.05723638070321425)),
 (24, np.float64(0.0)),
 (25, np.float64(0.0)),
 (26, np.float64(0.04559607525875532)),
 (27, np.float64(0.13678822577626598)),
 (28, np.float64(0.10514994558491725)),
 (29, np.float64(0.06003002251876642)),
 (30, np.float64(0.09913631941932194)),
 (31, np.float64(0.041424651066746664)),
 (32, np.float64(0.1823843010350213)),
 (33, np.float64(0.08718572905786445)),
 (34, np.float64(0.039872611141445)),
 (35, np.float64(0.03224129401095805)),
 (36, np.float64(0.0)),
 (37, np.float64(0.036760731104690386)),
 (38, np.float64(0.0)),
 (39, np.float64(0.10959932487023819)),
 (40, np.float64(0.2256354947537551)),
 (41, np.float64(0.1389425035941821)),
 (42, np.float64(0.07009996372327816)),
 (43, np.float64(0.12119654139092992)),
 (44, np.float64(0.03163859985841663)),
 (45, np.float64(0.09491579957524991)),
 (46, np.float64(0.047457899787624956)),
 (47, np.float64(0.0)),
 (48, np.float64(0.03224129401095805)),
 (49, np.float64(0.0)),
 (50, np.float64(0.0)),
 (51, np.float64(0.24002133617819926)),
 (52, np.float64(0.2790404591875126)),
 (53, np.float64(0.1316245316231641)),
 (54, np.float64(0.13513513513513514)),
 (55, np.float64(0.19827263883864388)),
 (56, np.float64(0.1643989873053573)),
 (57, np.float64(0.04393747751637468)),
 (58, np.float64(0.15404884978892905)),
 (59, np.float64(0.11510231387903269)),
 (60, np.float64(0.056388387443460086)),
 (61, np.float64(0.16120647005479025)),
 (62, np.float64(0.028618190351607124)),
 (63, np.float64(0.0)),
 (64, np.float64(0.0)),
 (65, np.float64(0.0)),
 (66, np.float64(0.20518233866439894)),
 (67, np.float64(0.0)),
 (68, np.float64(0.0)),
 (69, np.float64(0.042098266797411445)),
 (70, np.float64(0.07174960033341753)),
 (71, np.float64(0.09863939238321438)),
 (72, np.float64(0.09320546490018)),
 (73, np.float64(0.17170914210964275)),
 (74, np.float64(0.03163859985841663)),
 (75, np.float64(0.0)),
 (76, np.float64(0.2102998911698345)),
 (77, np.float64(0.02567480829815484)),
 (78, np.float64(0.2990445835608375)),
 (79, np.float64(0.1643989873053573)),
 (80, np.float64(0.03224129401095805)),
 (81, np.float64(0.0)),
 (82, np.float64(0.09863939238321438)),
 (83, np.float64(0.2442250043490654)),
 (84, np.float64(0.16916516233038026)),
 (85, np.float64(0.07749842582921286)),
 (86, np.float64(0.059053859535749265)),
 (87, np.float64(0.0)),
 (88, np.float64(0.0)),
 (89, np.float64(0.0)),
 (90, np.float64(0.08458258116519013)),
 (91, np.float64(0.07897471897389846)),
 (92, np.float64(0.0)),
 (93, np.float64(0.0)),
 (94, np.float64(0.09158437663089952)),
 (95, np.float64(0.0)),
 (96, np.float64(0.0)),
 (97, np.float64(0.03163859985841663)),
 (98, np.float64(0.2256354947537551)),
 (99, np.float64(0.06575959492214292)),
 (100, np.float64(0.09004503377814962)),
 (101, np.float64(0.09394227846020416)),
 (102, np.float64(0.056388387443460086)),
 (103, np.float64(0.03163859985841663)),
 (104, np.float64(0.0)),
 (105, np.float64(0.0533380747062665)),
 (106, np.float64(0.050734628943184104)),
 (107, np.float64(0.0)),
 (108, np.float64(0.03163859985841663)),
 (109, np.float64(0.07352146220938077)),
 (110, np.float64(0.028618190351607124)),
 (111, np.float64(0.11624763874381927)),
 (112, np.float64(0.0)),
 (113, np.float64(0.0885807893036239)),
 (114, np.float64(0.03106848830006)),
 (115, np.float64(0.02632490632463282)),
 (116, np.float64(0.09158437663089952)),
 (117, np.float64(0.027399831217559546)),
 (118, np.float64(0.07974522228289)),
 (119, np.float64(0.059053859535749265)),
 (120, np.float64(0.10514994558491725)),
 (121, np.float64(0.058123819371909635)),
 (122, np.float64(0.028618190351607124)),
 (123, np.float64(0.1061190899945022)),
 (124, np.float64(0.0)),
 (125, np.float64(0.08219949365267865)),
 (126, np.float64(0.12392039927415242)),
 (127, np.float64(0.14763464883937316)),
 (128, np.float64(0.036760731104690386)),
 (129, np.float64(0.0)),
 (130, np.float64(0.0)),
 (131, np.float64(0.18009006755629928)),
 (132, np.float64(0.13678822577626598)),
 (133, np.float64(0.14704292441876154)),
 (134, np.float64(0.0)),
 (135, np.float64(0.08489527199560176)),
 (136, np.float64(0.02567480829815484)),
 (137, np.float64(0.09802861627917438)),
 (138, np.float64(0.0)),
 (139, np.float64(0.2071841649822589)),
 (140, np.float64(0.2657423679108717)),
 (141, np.float64(0.10397504898200727)),
 (142, np.float64(0.0)),
 (143, np.float64(0.05479966243511909)),
 (144, np.float64(0.0)),
 (145, np.float64(0.11510231387903269)),
 (146, np.float64(0.03874921291460643)),
 (147, np.float64(0.0)),
 (148, np.float64(0.0533380747062665)),
 (149, np.float64(0.0)),
 (150, np.float64(0.0)),
 (151, np.float64(0.0)),
 (152, np.float64(0.08787495503274936)),
 (153, np.float64(0.1139901881468883)),
 (154, np.float64(0.08000711205939975)),
 (155, np.float64(0.0)),
 (156, np.float64(0.09592022754223367)),
 (157, np.float64(0.0)),
 (158, np.float64(0.11624763874381927)),
 (159, np.float64(0.18599622199011084)),
 (160, np.float64(0.0)),
 (161, np.float64(0.0)),
 (162, np.float64(0.056388387443460086)),
 (163, np.float64(0.055577001437672836)),
 (164, np.float64(0.10762440050012628)),
 (165, np.float64(0.10397504898200727)),
 (166, np.float64(0.0)),
 (167, np.float64(0.0644825880219161)),
 (168, np.float64(0.0199363055707225)),
 (169, np.float64(0.16967515794730187)),
 (170, np.float64(0.06070834938872646)),
 (171, np.float64(0.0)),
 (172, np.float64(0.0)),
 (173, np.float64(0.0)),
 (174, np.float64(0.10701462561817378)),
 (175, np.float64(0.059053859535749265)),
 (176, np.float64(0.03355780276070122)),
 (177, np.float64(0.0)),
 (178, np.float64(0.06575959492214292)),
 (179, np.float64(0.0)),
 (180, np.float64(0.10959932487023819)),
 (181, np.float64(0.19771864882368606)),
 (182, np.float64(0.09863939238321438)),
 (183, np.float64(0.16673100431301852)),
 (184, np.float64(0.03427955850955305)),
 (185, np.float64(0.2650854018430104)),
 (186, np.float64(0.09299811099505542)),
 (187, np.float64(0.1342312110428049)),
 (188, np.float64(0.0)),
 (189, np.float64(0.0)),
 (190, np.float64(0.059053859535749265)),
 (191, np.float64(0.12253577034896797)),
 (192, np.float64(0.24609055357847556)),
 (193, np.float64(0.05405405405405406)),
 (194, np.float64(0.08718572905786445)),
 (195, np.float64(0.14704292441876157)),
 (196, np.float64(0.0)),
 (197, np.float64(0.15660307954993902)),
 (198, np.float64(0.04901430813958719)),
 (199, np.float64(0.024784079854830485)),
 (200, np.float64(0.07218053273850816)),
 (201, np.float64(0.06575959492214292)),
 (202, np.float64(0.21029989116983447)),
 (203, np.float64(0.06327719971683327)),
 (204, np.float64(0.0)),
 (205, np.float64(0.0)),
 (206, np.float64(0.0)),
 (207, np.float64(0.0)),
 (208, np.float64(0.0)),
 (209, np.float64(0.1311450235388945)),
 (210, np.float64(0.0)),
 (211, np.float64(0.10067340828210367)),
 (212, np.float64(0.11810771907149853)),
 (213, np.float64(0.024507154069793594)),
 (214, np.float64(0.04474373701426829)),
 (215, np.float64(0.0)),
 (216, np.float64(0.1526406277181659)),
 (217, np.float64(0.0)),
 (218, np.float64(0.0)),
 (219, np.float64(0.07897471897389846)),
 (220, np.float64(0.15042366316917005)),
 (221, np.float64(0.09695723311274393)),
 (222, np.float64(0.025993762245501817)),
 (223, np.float64(0.06575959492214292)),
 (224, np.float64(0.059053859535749265)),
 (225, np.float64(0.10146925788636821)),
 (226, np.float64(0.07798128673650545)),
 (227, np.float64(0.12427395320024)),
 (228, np.float64(0.0)),
 (229, np.float64(0.05479966243511909)),
 (230, np.float64(0.050141221056390024)),
 (231, np.float64(0.03874921291460643)),
 (232, np.float64(0.2632490632463282)),
 (233, np.float64(0.03287979746107146)),
 (234, np.float64(0.0885807893036239)),
 (235, np.float64(0.11389895949029986)),
 (236, np.float64(0.23249527748763857)),
 (237, np.float64(0.14165281524036175)),
 (238, np.float64(0.0)),
 (239, np.float64(0.0)),
 (240, np.float64(0.055577001437672836)),
 (241, np.float64(0.21919864974047637)),
 (242, np.float64(0.03771571432023571)),
 (243, np.float64(0.04433510985214727)),
 (244, np.float64(0.0)),
 (245, np.float64(0.0)),
 (246, np.float64(0.022371868507134143)),
 (247, np.float64(0.06213697660012)),
 (248, np.float64(0.0)),
 (249, np.float64(0.0)),
 (250, np.float64(0.06213697660012)),
 (251, np.float64(0.03106848830006)),
 (252, np.float64(0.2279803762937766)),
 (253, np.float64(0.18668326147193276)),
 (254, np.float64(0.07009996372327816)),
 (255, np.float64(0.1289651760438322)),
 (256, np.float64(0.06003002251876642)),
 (257, np.float64(0.10067340828210367)),
 (258, np.float64(0.0)),
 (259, np.float64(0.148916158209988)),
 (260, np.float64(0.14097096860865022)),
 (261, np.float64(0.08458258116519013)),
 (262, np.float64(0.18494886071852695)),
 (263, np.float64(0.14763464883937316)),
 (264, np.float64(0.13949716649258315)),
 (265, np.float64(0.0)),
 (266, np.float64(0.1898315991504998)),
 (267, np.float64(0.09913631941932194)),
 (268, np.float64(0.1454358496691159)),
 (269, np.float64(0.25070610528195014)),
 (270, np.float64(0.08219949365267865)),
 (271, np.float64(0.18983159915049982)),
 (272, np.float64(0.0)),
 (273, np.float64(0.18790823039834775)),
 (274, np.float64(0.03163859985841663)),
 (275, np.float64(0.13181243254912406)),
 (276, np.float64(0.0)),
 (277, np.float64(0.19827263883864388)),
 (278, np.float64(0.03287979746107146)),
 (279, np.float64(0.07897471897389846)),
 (280, np.float64(0.03001501125938321)),
 (281, np.float64(0.0)),
 (282, np.float64(0.08489527199560176)),
 (283, np.float64(0.0)),
 (284, np.float64(0.09863939238321438)),
 (285, np.float64(0.16916516233038026)),
 (286, np.float64(0.07352146220938077)),
 (287, np.float64(0.15949044456578)),
 (288, np.float64(0.0)),
 (289, np.float64(0.14543584966911588)),
 (290, np.float64(0.0)),
 (291, np.float64(0.03287979746107146)),
 (292, np.float64(0.1485667259923031)),
 (293, np.float64(0.08718572905786445)),
 (294, np.float64(0.08458258116519013)),
 (295, np.float64(0.0)),
 (296, np.float64(0.02279803762937766)),
 (297, np.float64(0.07543142864047142)),
 (298, np.float64(0.06367145399670132)),
 (299, np.float64(0.14091341769030624)),
 (300, np.float64(0.06105625108726635)),
 (301, np.float64(0.05479966243511909)),
 (302, np.float64(0.039872611141445)),
 (303, np.float64(0.03163859985841663)),
 (304, np.float64(0.0)),
 (305, np.float64(0.04109974682633932)),
 (306, np.float64(0.13181243254912406)),
 (307, np.float64(0.08561170049453902)),
 (308, np.float64(0.03287979746107146)),
 (309, np.float64(0.09863939238321438)),
 (310, np.float64(0.05134961659630968)),
 (311, np.float64(0.07009996372327816)),
 (312, np.float64(0.09032775043542898)),
 (313, np.float64(0.036760731104690386)),
 (314, np.float64(0.12683657235796025)),
 (315, np.float64(0.17155007848855516)),
 (316, np.float64(0.0685591170191061)),
 (317, np.float64(0.13812277665483924)),
 (318, np.float64(0.08219949365267865)),
 (319, np.float64(0.15949044456578)),
 (320, np.float64(0.0)),
 (321, np.float64(0.09158437663089952)),
 (322, np.float64(0.05723638070321425)),
 (323, np.float64(0.0)),
 (324, np.float64(0.0863465783552691)),
 (325, np.float64(0.0)),
 (326, np.float64(0.1354916256531435)),
 (327, np.float64(0.10514994558491725)),
 (328, np.float64(0.06003002251876642)),
 (329, np.float64(0.0)),
 (330, np.float64(0.030528125543633176)),
 (331, np.float64(0.15499685165842572)),
 (332, np.float64(0.10810810810810811)),
 (333, np.float64(0.2029385157727364)),
 (334, np.float64(0.029526929767874632)),
 (335, np.float64(0.08787495503274936)),
 (336, np.float64(0.0)),
 (337, np.float64(0.0)),
 (338, np.float64(0.1342312110428049)),
 (339, np.float64(0.13949716649258312)),
 (340, np.float64(0.039872611141445)),
 (341, np.float64(0.2056773510573183)),
 (342, np.float64(0.03001501125938321)),
 (343, np.float64(0.2632490632463282)),
 (344, np.float64(0.02279803762937766)),
 (345, np.float64(0.0885807893036239)),
 (346, np.float64(0.06711560552140244)),
 (347, np.float64(0.10529962529853128)),
 (348, np.float64(0.0)),
 (349, np.float64(0.21010507881568247)),
 (350, np.float64(0.0)),
 (351, np.float64(0.0)),
 (352, np.float64(0.04901430813958719)),
 (353, np.float64(0.0)),
 (354, np.float64(0.0644825880219161)),
 (355, np.float64(0.15042366316917005)),
 (356, np.float64(0.04697113923010208)),
 (357, np.float64(0.09863939238321438)),
 (358, np.float64(0.03355780276070122)),
 (359, np.float64(0.19605723255834873)),
 (360, np.float64(0.08718572905786445)),
 (361, np.float64(0.17155007848855516)),
 (362, np.float64(0.03224129401095805)),
 (363, np.float64(0.15086285728094284)),
 (364, np.float64(0.10959932487023819)),
 (365, np.float64(0.09208185110322616)),
 (366, np.float64(0.0)),
 (367, np.float64(0.10397504898200727)),
 (368, np.float64(0.08489527199560176)),
 (369, np.float64(0.0)),
 (370, np.float64(0.0)),
 (371, np.float64(0.0)),
 (372, np.float64(0.08458258116519013)),
 (373, np.float64(0.0)),
 (374, np.float64(0.06711560552140244)),
 (375, np.float64(0.03771571432023571)),
 (376, np.float64(0.11624763874381927)),
 (377, np.float64(0.0)),
 (378, np.float64(0.050141221056390024)),
 (379, np.float64(0.08336550215650926)),
 (380, np.float64(0.0)),
 (381, np.float64(0.0)),
 (382, np.float64(0.07352146220938079)),
 (383, np.float64(0.0)),
 (384, np.float64(0.07974522228289)),
 (385, np.float64(0.0)),
 (386, np.float64(0.025993762245501817)),
 (387, np.float64(0.09119215051751065)),
 (388, np.float64(0.05134961659630968)),
 (389, np.float64(0.18857857160117855)),
 (390, np.float64(0.1606762634546782)),
 (391, np.float64(0.1186447494690624)),
 (392, np.float64(0.0)),
 (393, np.float64(0.0)),
 (394, np.float64(0.1559625734730109)),
 (395, np.float64(0.04109974682633932)),
 (396, np.float64(0.09394227846020416)),
 (397, np.float64(0.19727878476642874)),
 (398, np.float64(0.21137012653545936)),
 (399, np.float64(0.0)),
 (400, np.float64(0.0)),
 (401, np.float64(0.1342312110428049)),
 (402, np.float64(0.0)),
 (403, np.float64(0.0)),
 (404, np.float64(0.2324952774876386)),
 (405, np.float64(0.0)),
 (406, np.float64(0.0)),
 (407, np.float64(0.08489527199560176)),
 (408, np.float64(0.02632490632463282)),
 (409, np.float64(0.03504998186163908)),
 (410, np.float64(0.03427955850955305)),
 (411, np.float64(0.029061909685954818)),
 (412, np.float64(0.0)),
 (413, np.float64(0.0)),
 (414, np.float64(0.0644825880219161)),
 (415, np.float64(0.06105625108726635)),
 (416, np.float64(0.13678822577626595)),
 (417, np.float64(0.03224129401095805)),
 (418, np.float64(0.07543142864047142)),
 (419, np.float64(0.15794943794779692)),
 (420, np.float64(0.0)),
 (421, np.float64(0.0)),
 (422, np.float64(0.22555354977384034)),
 (423, np.float64(0.0)),
 (424, np.float64(0.0)),
 (425, np.float64(0.09158437663089952)),
 (426, np.float64(0.11314714296070713)),
 (427, np.float64(0.12683657235796025)),
 (428, np.float64(0.15404884978892902)),
 (429, np.float64(0.07352146220938077)),
 (430, np.float64(0.10514994558491725)),
 (431, np.float64(0.08219949365267865)),
 (432, np.float64(0.019374606457303215)),
 (433, np.float64(0.0)),
 (434, np.float64(0.11961783342433499)),
 (435, np.float64(0.039872611141445)),
 (436, np.float64(0.07352146220938077)),
 (437, np.float64(0.06213697660012)),
 (438, np.float64(0.059053859535749265)),
 (439, np.float64(0.06711560552140244)),
 (440, np.float64(0.0)),
 (441, np.float64(0.0885807893036239)),
 (442, np.float64(0.14763464883937316)),
 (443, np.float64(0.0)),
 (444, np.float64(0.0)),
 (445, np.float64(0.04109974682633932)),
 (446, np.float64(0.0)),
 (447, np.float64(0.03427955850955305)),
 (448, np.float64(0.2790404591875126)),
 (449, np.float64(0.036760731104690386)),
 (450, np.float64(0.03587480016670876)),
 (451, np.float64(0.1677890138035061)),
 (452, np.float64(0.18599622199011084)),
 (453, np.float64(0.11624763874381927)),
 (454, np.float64(0.02632490632463282)),
 (455, np.float64(0.1643989873053573)),
 (456, np.float64(0.17574991006549873)),
 (457, np.float64(0.1316245316231641)),
 (458, np.float64(0.0)),
 (459, np.float64(0.0)),
 (460, np.float64(0.0)),
 (461, np.float64(0.09158437663089952)),
 (462, np.float64(0.18065550087085797)),
 (463, np.float64(0.05405405405405406)),
 (464, np.float64(0.07543142864047142)),
 (465, np.float64(0.17574991006549873)),
 (466, np.float64(0.12655439943366653)),
 (467, np.float64(0.14019992744655632)),
 (468, np.float64(0.22581937608857244)),
 (469, np.float64(0.1526406277181659)),
 (470, np.float64(0.05479966243511909)),
 (471, np.float64(0.0)),
 (472, np.float64(0.0644825880219161)),
 (473, np.float64(0.0)),
 (474, np.float64(0.1252721535988985)),
 (475, np.float64(0.03874921291460643)),
 (476, np.float64(0.12006004503753284)),
 (477, np.float64(0.14704292441876154)),
 (478, np.float64(0.11810771907149853)),
 (479, np.float64(0.12655439943366653)),
 (480, np.float64(0.0)),
 (481, np.float64(0.0)),
 (482, np.float64(0.0)),
 (483, np.float64(0.0)),
 (484, np.float64(0.04559607525875532)),
 (485, np.float64(0.08585457105482137)),
 (486, np.float64(0.058123819371909635)),
 (487, np.float64(0.07974522228289)),
 (488, np.float64(0.07521183158458504)),
 (489, np.float64(0.0)),
 (490, np.float64(0.09913631941932194)),
 (491, np.float64(0.0)),
 (492, np.float64(0.0)),
 (493, np.float64(0.1553424415003)),
 (494, np.float64(0.08489527199560176)),
 (495, np.float64(0.0)),
 (496, np.float64(0.07174960033341753)),
 (497, np.float64(0.10514994558491725)),
 (498, np.float64(0.10514994558491725)),
 (499, np.float64(0.12329924047901797)),
 (500, np.float64(0.025993762245501817)),
 (501, np.float64(0.0)),
 (502, np.float64(0.059053859535749265)),
 (503, np.float64(0.14543584966911588)),
 (504, np.float64(0.05405405405405406)),
 (505, np.float64(0.09004503377814962)),
 (506, np.float64(0.03427955850955305)),
 (507, np.float64(0.08219949365267865)),
 (508, np.float64(0.050734628943184104)),
 (509, np.float64(0.08219949365267865)),
 (510, np.float64(0.07749842582921286)),
 (511, np.float64(0.047457899787624956)),
 (512, np.float64(0.05723638070321425)),
 (513, np.float64(0.0)),
 (514, np.float64(0.0)),
 (515, np.float64(0.0949157995752499)),
 (516, np.float64(0.1553424415003)),
 (517, np.float64(0.07352146220938077)),
 (518, np.float64(0.11961783342433499)),
 (519, np.float64(0.0)),
 (520, np.float64(0.1221125021745327)),
 (521, np.float64(0.0)),
 (522, np.float64(0.03587480016670876)),
 (523, np.float64(0.1841637022064523)),
 (524, np.float64(0.03355780276070122)),
 (525, np.float64(0.14349920066683505)),
 (526, np.float64(0.1221125021745327)),
 (527, np.float64(0.0)),
 (528, np.float64(0.0)),
 (529, np.float64(0.0)),
 (530, np.float64(0.0)),
 (531, np.float64(0.22147019900891643)),
 (532, np.float64(0.0)),
 (533, np.float64(0.23543217635998231)),
 (534, np.float64(0.05479966243511909)),
 (535, np.float64(0.08585457105482137)),
 (536, np.float64(0.04244763599780088)),
 (537, np.float64(0.20539846638523873)),
 (538, np.float64(0.11961783342433499)),
 (539, np.float64(0.22830583024432843)),
 (540, np.float64(0.03874921291460643)),
 (541, np.float64(0.0)),
 (542, np.float64(0.0)),
 (543, np.float64(0.039872611141445)),
 (544, np.float64(0.06213697660012)),
 (545, np.float64(0.14097096860865022)),
 (546, np.float64(0.07174960033341753)),

In [58]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:5]

[(837, np.float64(0.33557802760701216)),
 (15809, np.float64(0.31898088913156)),
 (12967, np.float64(0.3161471265240014)),
 (4075, np.float64(0.31511100761641775))]

In [59]:
df[df['title']=='Avatar'].index[0]

3

In [60]:
def recommend(movie):
    movie_index=df[df['title']==movie].index[0]
    distance=similarity[movie_index]
    movie_list=sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movie_list:
        print(df.iloc[i[0]].title)

In [61]:
recommend('Avatar')

Independence Day
Space Chimps 2: Zartog Strikes Back
Skylines
King Shakir Recycle
Mission to Mars

In [62]:
df['title'].values

<StringArray>
[                                                  'Inception',
                                                'Interstellar',
                                             'The Dark Knight',
                                                      'Avatar',
                                                'The Avengers',
                                                    'Deadpool',
                                      'Avengers: Infinity War',
                                                  'Fight Club',
                                     'Guardians of the Galaxy',
                                                'Pulp Fiction',
 ...
           'Manufacturing Consent: Noam Chomsky and the Media',
                                             'The Desert Rats',
 'WeWork: or The Making and Breaking of a $47 Billion Unicorn',
                                                     'RKO 281',
                                                'The Jackpot!',
                                                 'Midnight FM',
                                                   'Desi Boyz',
  'Legend of the Galactic Heroes: Die Neue These - Intrigue 1',
                                              'You Stupid Man',
                                           'The Hi-Lo Country']
Length: 21000, dtype: str

In [63]:
import pickle

In [64]:
with open (r"D:\Recommendation system\moviesimilarity.pkl","wb") as f:
    pickle.dump(similarity,f)